apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-clusters-prod
spec:
  argoServer:
    cluster: prod-clusters
    argoNamespace: acm-gitops-prod
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: prod-clusters
