apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acm-gitops-prod

resources:
  - namespace.yaml
  - managedclusterset.yaml     
  - gitops.yaml  
  - placement.yaml
  - gitops-cluster.yaml
  - managedclusterset-bindings.yaml
  - argo-acm-role.yaml
  - argo-acm-rb.yaml
