apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: prod-clusters
  namespace: acm-gitops-prod
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: "In"
          values:
          - local-cluster
