apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: placementdecisions-reader-role
rules:
- apiGroups: ["cluster.open-cluster-management.io"] 
  resources: ["placementdecisions"]
  verbs: ["get", "watch", "list"]
