apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-clusters-dev
spec:
  argoServer:
    cluster: dev-clusters
    argoNamespace: acm-gitops-dev
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: dev-clusters
